Feature/workflow test
wasedatime/wasedatime-web pull request #219
Opened 2021-06-30 06:42 UTC by Allen931

Fix GitHub actions

2021-06-30 08:40 UTC, AustinZhu requested changes
You can either:
1. keep the dummy test files and remove the test phase in CI.
2. keep the test phase in CI and make the condition in the test always true.

If you use `--passWithNoTests`, others might not be aware of that.
If you delete all the dummy test files, later people will need to create them from scratch.

2021-06-30 08:40 UTC, AustinZhu commented on .github/workflows/node.js.yml
> +          npm run test-all
You can just remove this step.

2021-06-30 08:40 UTC, AustinZhu commented on blog/package.json
> +    "test": "cross-env BABEL_ENV=test jest --passWithNoTests",
Instead of force npm to pass the test, you just need to remove the test phase in CI.

2021-06-30 08:40 UTC, AustinZhu commented on campus/package.json
> +    "test": "cross-env BABEL_ENV=test jest --passWithNoTests",
1. What if someone writes a test and want to run it locally? -> He might find the test passes anyway.
2. What if later we have the test phase in CI? -> All these args need to be removed.

2021-06-30 08:40 UTC, AustinZhu commented on blog/src/root.component.test.tsx
> -});
Keep these dummy test files.

2021-07-07 22:55 UTC, AustinZhu commented
@Allen931 How's everything going?

2021-07-08 11:00 UTC, Allen931 commented
Added test cases. Sorry for being so late.

2021-07-08 11:07 UTC, AustinZhu commented on campus/package.json
> +    "test": "cross-env BABEL_ENV=test jest --passWithNoTests",
> 1. What if someone writes a test and want to run it locally? -> He might find the test passes anyway.
> 2. What if later we have the test phase in CI? -> All these args need to be removed.

@Allen931 Please DO NOT use --passWithNoTests

2021-07-08 11:08 UTC, AustinZhu commented
> Added test cases. Sorry for being so late.

[Did you see this?](https://github.com/wasedatime/wasedatime-web/pull/219#discussion_r666094770)

2021-07-08 11:13 UTC, Allen931 commented
Sorry for the previous mistake, I thought I fix it.

2021-07-08 11:19 UTC, AustinZhu commented
Can you use path in on_push event? Now even if someone makes a small change in a micro-app repo, all micro-apps need to be build.
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

2021-07-08 11:27 UTC, merged