feat: add new members
wasedatime/wasedatime-web pull request #298
Opened 2022-02-24 14:27 UTC by momo296

Update the members' page.

## Description

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-03-06 12:51 UTC, YHhaoareyou commented
I just rebased it to `develop`

2022-03-08 14:14 UTC, nichnarmada requested changes
Please check my comments!

2022-03-09 06:03 UTC, momo296 commented on root/src/components/aboutUs/MeetOurTeam/MeetOurTeam.tsx
> +  margin: 40px 30px 30px;
Sure!

2022-03-11 00:56 UTC, nichnarmada approved these changes

2022-03-11 02:38 UTC, YHhaoareyou approved these changes
LGTM

2022-03-11 02:39 UTC, merged